basic (and a bit broken) path extracting
yandex/cggen pull request #39
Opened 2022-12-07 01:23 UTC by alexxingplus

2022-12-20 11:14 UTC, chizberg commented on Sources/BCCommon/Command.swift
> +import CoreGraphics
it wouldn't build without that :(

2022-12-20 11:14 UTC, chizberg commented on Sources/BCRunner/BytecodeReaders.swift
> +  where Self: RawRepresentable, RawValue: FixedWidthInteger {
swiftformat did this, not me

2022-12-20 11:14 UTC, chizberg commented on Tests/RegressionTests/PathExtractionSupport.swift
> +  let svgString = svgString(
the initial idea was to take a CGPath -> create an SVG -> and then get CGPath from it again to compare with initial one

but then i've found that I can't test some elements like smoothCurve because they are not CGPath elements.

2022-12-20 11:14 UTC, chizberg commented on Tests/RegressionTests/PathExtractionSupport.swift
> +  func isAlmostEqual(to other: PathSegment, tolerance: CGFloat) -> Bool {
i really hope we will eventually get rid of it..

2022-12-20 11:14 UTC, chizberg commented on Tests/RegressionTests/BCCompilationTests.swift
> +//      "path_smooth_curve_defs.svg",
should be removed

2022-12-20 11:14 UTC, chizberg commented on Tests/RegressionTests/SVGTests.swift
> +      startAngle: -.pi / 2,
- Why do we need to compare cgPaths with tolerance?

There's an issue with these π angles. We lose some data while encoding and decoding - that's why we have a tiny bit different angle at decoding. Also addArc() method of CGPath splits the arc into two curves, so many numbers are a bit off. I think I can't get rid of this irrationality in the tests

2022-12-20 14:40 UTC, zienag requested changes
Looks very promising! Just a couple improvements in comments

2022-12-20 14:40 UTC, zienag commented on Tests/RegressionTests/PathExtractionSupport.swift
> +    default: return false
It's better to list all possible cases here for compiler to notice when new case will be added:
```
case (.moveTo, _), (. lineTo, _), (.curveTo, _) ...:
  return false
```

2022-12-20 14:40 UTC, zienag commented on Tests/RegressionTests/SVGTests.swift
> +//    test(args: circlesAndRectsArgs)
uncomment or delete?

2022-12-20 18:49 UTC, alexxingplus commented
I've just noticed failing `testNestedTransparentGroup` test, at the moment I don't quite understand why would it fail

2022-12-22 14:57 UTC, zienag approved these changes

2022-12-22 14:57 UTC, merged